package db

import "log/slog"

// S3Object represents the metadata of a file stored in Amazon S3,
// mirrored in our PostgreSQL database for fast searching.
type S3Object struct {
	// ID is the unique database serial primary key.
	ID int `json:"id"`

	// FileKey is the full path/name of the object in the S3 bucket.
	// This is marked as UNIQUE in the database.
	FileKey string `json:"file_key"`

	// FileSize represents the size of the object in bytes.
	FileSize int64 `json:"file_size"`

	// LastModified is the ISO8601 string of when the object was last changed in S3.
	LastModified string `json:"last_modified"`

	// ETag is the entity tag (usually an MD5 hash) of the S3 object.
	ETag string `json:"etag"`

	// Similarity is a calculated score (0.0 to 1.0) returned by pg_trgm 
	// during fuzzy searches. It is omitted from JSON if not part of a search result.
	Similarity float32 `json:"similarity,omitempty"`

	// DownloadURL is a temporary, signed CloudFront URL generated on-the-fly.
	// It is omitted from JSON if not explicitly generated by the signer.
	DownloadURL string `json:"download_url,omitempty"`
}

// LogValue allows S3Object to be passed directly to slog functions.
// This implements the slog.LogValuer interface, ensuring sensitive 
// data can be filtered or formatted specifically for logs.
func (o S3Object) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("key", o.FileKey),
		slog.Int64("size", o.FileSize),
		slog.Float64("score", float64(o.Similarity)),
	)
}